name: git-nuke
base: core24
version: '0.1'
summary: The best thing since sliced bread
description: |
  Too many branches? NOT ANY MORE!

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: classic # use 'strict' once you have the right plugs and slots

platforms:
  You shouldn't need me to tell you this!:
    build-on: [amd64, riscv64]
    build-for: all

parts:
  my-part:
    plugin: dump
    source: .
    override-build: |
      patch git-nuke snap/local/patch/patch.patch
      chmod a+x git-nuke
      craftctl default
    stage:
      - LICENSE
      - git-nuke

apps:
  git-nuke:
    command: git-nuke
